### ISSUE TITLE
Request: Viewer count

### ISSUE THREAD

**Issue by Voletek** [jprjr/docker-multistreamer#10]
it would be great if there was a feature to add a live viewer count to the from the various services

**Comment by jprjr** [comment]
There is! When you're in the combined chat window there's viewer counts along the top. You can also get to them via IRC

**Comment by Voletek** [comment]
I guess I must have missed it!

Have you tested if it's possible to pull the game titles in the fields in a dropdown instead of physically typing them.. I know from the different services they have some games listed differently. Also if they the game isn't exact the video stream won't be found on that platform

**Comment by jprjr** [comment]
It's definitely do-able. All the services provide an API for querying games. I just have to look into using some javascript library to do auto-completion.

I'm hoping my free time will clear up a bit in the next week or two - I just moved across the country and my house is still a total disaster, haha

**Comment by Voletek** [comment]
I just had a crazy thought.. i don't know alot about Lua or open-resty I've been looking through the elua files and noticed there isn't a page for admins to monitor the streams health... Nginx has a module that uses xsl to pull the streams into an xml format that displays the statistics does your platform have the same ability?

**Comment by jprjr** [comment]
That should be doable, too - under the hood, I'm just using the nginx RTMP module. It shouldn't be too hard to get at that data and extract details on the stream's inputs and outputs.

**Comment by Voletek** [comment]
Your all in one setup script worked amazingly btw. I attempted to use the docker image and I think my box was incompatible... I also noticed the script only uses Ubuntu, fortunately I just quickly setup an aws image to do some testing do you have plans on supporting other Linux distros in the future.

**Comment by jprjr** [comment]
Hey, we've gotten a bit off-track in this issue. I only have plans to support Ubuntu over in https://github.com/jprjr/multistreamer-installer, the Docker version is my method of supporting other distros.

I'll go ahead and open an issue in the main Multistreamer repo for showing stream bitrate: https://github.com/jprjr/multistreamer/issues/35
