### ISSUE TITLE
Installation on an already running nginx vps ?

### ISSUE THREAD

**Issue by rubensben** [jprjr/docker-multistreamer#16]
Please check this issue : https://github.com/jprjr/multistreamer-installer/issues/11

**Comment by rubensben** [comment]
In order to help me to fix this, is there any LAMP configuration that the docker's host should have in order to make it work ?

**Comment by rubensben** [comment]
I believe I may have found something looking into /srv/docker/multistreamer/multistreamer/config.yaml file : 
```
### path to your nginx+lua+rtmp binary
nginx: '/opt/openresty/nginx/sbin/nginx'
```

Where on my host, nginx is on /usr/sbin/nginx

**Comment by rubensben** [comment]
ok not coming from that, I tried to do a simlink but no changes. By the way the port 6667 is also closed (IRC), so it's not coming from nginx / rtmp but something else. I really don't understand since the ports seems to be open when checking them on the terminal. Something must be wrong between the docker and the firewall / network

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
