### ISSUE TITLE
Config Persistence after restart

### ISSUE THREAD

**Issue by 0x41mmarVM** [jprjr/docker-multistreamer#18]
Hi, 
Thank you very much for the amazing work. Multistreamer has been very helpful to me and my team.
I'm currently running Multistreamer using docker compose with minimal configuration. I've created a systemd service file for it, and it runs at startup and works beautifully; users being created on the fly at the first login attempt is just fine for my usecase. However, every time the service is restarted users lose all the config they had created in their accounts. 

* What would be the quickest way for config to persist across restarts?
* I'm thinking I'll keep a proper postgresql running and link it instead of starting the default postgre container, would that work?

Thanks a lot.

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
