### ISSUE TITLE
Update with main repo to fix twitch

### ISSUE THREAD

**Issue by Arcanum417** [jprjr/docker-multistreamer#19]
It would be nice to get this updated for this fix to work https://github.com/jprjr/multistreamer/commit/933ef7dd6f6cc12e7a8308dd4abfc0e6aeb02a18

As of now this image has twitch auth broken.

**Comment by amasu** [comment]
check https://github.com/jprjr/docker-multistreamer/issues/22

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
