### ISSUE TITLE
When run with docker-compose quickstart, create custom rtmp url(youtube), stream video is not shown on youtube

### ISSUE THREAD

**Issue by babkamen** [jprjr/docker-multistreamer#2]
Can see steam on web UI, but not on Youtube page
In config.lua I can see rtmp = true
Is there a way to debug it?

**Comment by jprjr** [comment]
Oh man, this one is embarrassing. Before version 6, Multistreamer would call the pusher lua script directly, but starting with version 6, it calls the bash wrapper script instead. When I updated to version 6, I forgot to add the bash script to the docker image.

Additionally, I accidentally committed a line where I commented-out some logging when processes ended. I just pushed up a new tag to multistreamer and a new tag here, that should fix the pushing code. Give it a try and let me know!

**Comment by babkamen** [comment]
Yep! It works. Thanks!

**Comment by jprjr** [comment]
Hey, thanks for the feedback!
