### ISSUE TITLE
Not authenticate against Facebook - Facebook not working

### ISSUE THREAD

**Issue by bentech4u** [jprjr/docker-multistreamer#20]
HI,

i tried to install docker based installation and i am getting the page and application,

When i click the Facebook, it is redirecting to facebook but it's not working peoperly,
my facebook like look like below:

"https://www.facebook.com/v3.0/dialog/oauth?redirect_uri=https%3A%2F%2Fdiykuwait.com%3A8081%2Fauth%2Ffacebook&client_id=250567575972981&state=ZXlKcFpDSTZNWDA9LkJ6R01ZV2dBUHQrY3VVcmcxdUtpU3RmdjI2UT0%3D&scope=publish_video%2Cuser_events%2Cmanage_pages%2Cpublish_pages"

and the redirect url has 8081 port , 

Nginx conf file:
https://pastebin.com/KrB956vW

and my docker file:

https://pastebin.com/47KYXtQH

**Comment by bentech4u** [comment]
and it's the same thing for youtube alos,

The redirect URI in the request, https://diykuwait.com:8081/auth/youtube, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/860269803929-fjrl0v22pea7k259n6lnppms1k3gk9r4.apps.googleuserconte

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
