### ISSUE TITLE
Error 400 'the scope you are requesting is currently unavailable' when adding a new twitch account

### ISSUE THREAD

**Issue by amasu** [jprjr/docker-multistreamer#22]
Hello,
I would like to report the following issue I am encoutering:
Adding a Twitch account from multistreamer UI leads to the error mentioned in the title.
I have done the following as configuration:
* I've created an app on dev.twitch.tv
* I've added the client ID, Secret key, and rtmp to the yml config file of docker compose.
* I've authorized the redirect URL 'https://<mywebsite.com>/auth/twitch' in the twitch console.
* I've checked that the URL is publicly exposed (in fact, I could add a facebook and a youtube account using the same URL pattern).

I think the issue is caused by the use of a deprecated scope '**chat_login**' which is deprecated in the V5 of Twitch API according to [official doc](https://dev.twitch.tv/docs/v5/guides/migration#scopes).
This probably still works for old client IDs, but not for new ones...

Anyone experiencing some similar issue?

### Error message:
`{"status":400,"message":"Sorry, the scope you are requesting is currently unavailable. Please request new scopes documented at https://dev.twitch.tv/docs/authentication/#chat-and-pubsub."}`

**Comment by amasu** [comment]
I actually found a workaround, I just want to share and maybe to trigger a commit ;)

The issue was solved by replacing the scope 'chat_login' with 'chat:read' (or chat:edit) in the 'Add New Twitch' URL:
`https://api.twitch.tv/kraken/oauth2/authorize?response_type=code&client_id=nzljnq3hni4jowmlai8pkiq141oqg6&force_verify=true&redirect_uri=https%3A%2F%2F**<yourdomain.com>**%2Fauth%2Ftwitch&scope=user_read%20channel_read%20channel_editor%20channel_stream%20chat%3Aread&state=ZXlKcFpDSTZNWDA9Lm44YkdhZEFRbHJNMXU2cGpnTFcxTm1vc3NDMD0%3D`

I will not close the issue so that it is visible to whom it might interest. If it bother please feel free to close.

Thanks and stay safe!

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
