### ISSUE TITLE
Port Binding Issue

### ISSUE THREAD

**Issue by encausticcello** [jprjr/docker-multistreamer#23]
Hi, I'm able to get this working locally, but want to test it out on an external web server. When I run the docker container itself, it's binding port 8080 to localhost:

tcp  0  0 127.0.0.1:8080  0.0.0.0:* LISTEN

Is there a way to force the app to bind to 0.0.0.0:8080 instead? Maybe there's an environment var that could be used?

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
