### ISSUE TITLE
Stop pushing stream not working properly

### ISSUE THREAD

**Issue by rerdogantr** [jprjr/docker-multistreamer#27]
Hi @jprjr 

Thank you for contributing for stream world.

It is working good right now except stopping streaming button.
For example, First we are sending stream with OBS to docker MULTISTREAMER. After this i created CUSTOM RTMP and pushing stream to facebook. No problem. When i clicked to STOP button, MULTISTREAMER shows has been stopped.

But on Facebook stream still standing. I should stop or restart container for stopping it.
What should i do for this ?

Thanks

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
