### ISSUE TITLE
When add youtube variables to docker-compose cannot see additional option on web UI

### ISSUE THREAD

**Issue by babkamen** [jprjr/docker-multistreamer#3]
Is there anything else I need to do? In config.lua I cannot see additional configuration

**Comment by jprjr** [comment]
It looks like I had a bug in my startup script where I was checking for some non-existent variables. Just pushed a new tag (6.1.2-2), this should fix both #2 and this issue. Give it a try and let me know if it works

**Comment by jprjr** [comment]
This has been fixed for some time, closing.
