### ISSUE TITLE
not pushing to some Cutom RTMP like Mips.tv

### ISSUE THREAD

**Issue by mourin00** [jprjr/docker-multistreamer#5]
i tested multistreamer and work fine with youtube, vk ,fb ... but not pushing to some Cutom RTMP like Mips.tv

**Comment by jprjr** [comment]
I'm not familiar with mips - do they require authentication or anything like that? Do they have any tutorials on say, setting up OBS/Xsplit I can take a look at?

**Comment by mourin00** [comment]
they dont request authentication and wihtout any tutorials or setting they just give me FMS URL : rtmp://cdn.mipspublisher.com/live and Stream Name : .... and it work fine in OBS

**Comment by jprjr** [comment]
This issue was moved to jprjr/multistreamer#36
