### ISSUE TITLE
ARM Support?

### ISSUE THREAD

**Issue by pogzie** [jprjr/docker-multistreamer#8]
I tried running this by following the long 45 minute guide, but it seems like im encountering `multistreamer_1  | standard_init_linux.go:178: exec user process caused "exec format error"` which I assume is due to libraries or components built for x86. 

Can you build a version thats ARM friendly?

**Comment by jprjr** [comment]
I can create a Dockerfile that's ARM-friendly, but I'm not sure how to build and distribute it. Do most ARM users expect their Docker images to be on Docker Hub? I usually use the automated build feature of Docker hub, but AFAIK that's x86_64-only.

**Comment by pogzie** [comment]
There are a bunch of Raspberry Pi images in Dockerhub so I assume they support it. Greatly appreciate if you can do an ARM build. Thanks!

**Comment by jprjr** [comment]
Hey, I did some research and figured out how to create multi-arch images, and found a technique for running qemu on Docker hub, so I can still have automatic builds.

If you try pulling down the latest tag (11.0.6-2), it should automatically pick the right image for your Raspberry Pi.

This is *entirely* untested on an actual Pi so your mileage may vary.

**Comment by pogzie** [comment]
I havent tested the recommendations from the other repo. I will make time and test it and see if we can get an arm version of the docker image.

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
