### ISSUE TITLE
Issue on Deployment

### ISSUE THREAD

**Issue by pogzie** [jprjr/docker-multistreamer#9]
Ok, take a seat, get some coffee cause this going to be a long one. 

I had problems with deploying Multistreamer via a VM in my ESXi machine so I decided to something more robust like deploying it on the pretty amazing Mesosphere's DC/OS ;). At first I had to mangle through creating an app definition to launch the docker-multistreamer image, then work my way into setting/passing the environment variables, then upon checking the `stderr` and `stdout` of the launched docker-multistreamer I noticed that I needed a Redis and a Postgres deployment, two clicks and I have the two running on DC/OS without any problems. I made sure that the hostnames are reachable from where im launching Multistreamer and boom, got the UI up and running. 

Until that little `Unrecoverable error! Please check logs and restart Multistreamer ` error popped out. I checked my DC/OS multistreamer `stderr` and `stdout`, its clean. I had to jump into the node running the Multistreamer container and do a `docker exec` just to get a shell into the running container. I checked `/var/log/multistreamer` on what ails this deployment, lo and behold: 

```
2018-02-23 10:27:57.652930500  	[C]: in function 'wait'
2018-02-23 10:27:57.652930500  	init_worker_by_lua:12: in function <init_worker_by_lua:7>, context: ngx.timer
2018-02-23 10:27:57.653227500  2018/02/23 10:27:57 [error] 359#359: *12 stream lua user thread aborted: runtime error: ...streamer/lua_modules/share/lua/5.1/lapis/db/postgres.lua:58: postgresql.marathon.l4lb.thisdcos.directory could not be resolved (3: Host not found)
2018-02-23 10:27:57.653230500  stack traceback:
2018-02-23 10:27:57.653231500  coroutine 0:
```

Which _is_ a bit weird. I know DC/OS takes care of the load balancing to its deployed services and I even checked if I could reach it while inside the container: 

```
bash-4.3# ping postgresql.marathon.l4lb.thisdcos.directory
PING postgresql.marathon.l4lb.thisdcos.directory (11.255.191.179): 56 data bytes
64 bytes from 11.255.191.179: seq=0 ttl=64 time=0.035 ms
64 bytes from 11.255.191.179: seq=1 ttl=64 time=0.057 ms
```

I might be hitting what you said about `/etc/hosts` file but I cant be too sure 

> When you use container linking, Docker updates the /etc/hosts file with hostnames, but nginx ignores that file, and strictly looks up hosts via DNS.

Doing some Googling and I found this: https://github.com/openresty/openresty/issues/298 

So if its a lookup error, is there any workaround for this?

**Comment by pogzie** [comment]
I tired testing using the IP address of the node where my Postgres is deployed, upon checking `/var/log/multistreamer/current` looks like Redis is suffering the same issue: 

```
2018-02-23 10:47:09.637187500  2018/02/23 10:47:09 [error] 359#359: *9 [lua] redis.lua:39: subscribe(): Redis:subscribe: Unable to connect to redis: redis.marathon.l4lb.thisdcos.directory:6379 could not be resolved (3: Host not found), context: ngx.timer
2018-02-23 10:47:09.637195500  2018/02/23 10:47:09 [error] 359#359: *9 [lua] process_manager.lua:98: run(): [Process Manager] Unable to connect to redis: redis.marathon.l4lb.thisdcos.directory:6379 could not be resolved (3: Host not found), context: ngx.timer
```
I've set it as the IP address too in the Multistreamer app definition along with a non changing port for both services. Looks like its clear: 

```
bash-4.3# cat /var/log/multistreamer/current 
2018-02-23 10:50:30.225331500  Ran 0 migrations
```

So whats the workaround so I can use a DNS name for this?

**Comment by pogzie** [comment]
I might have found the correct IPs from https://docs.mesosphere.com/1.10/overview/design/dns-proxy/#dns-forwarder-interface

Setting `"MULTISTREAMER_DNS_RESOLVER" : "198.51.100.1 198.51.100.2 198.51.100.3 ipv6=off"` doesnt seem to work. 

Back to the drawingboard.

**Comment by pogzie** [comment]
After doing some tests, using one of the IPs above is getting correct resolution. Is this possibly a conversion problem that `MULTISTREAMER_DNS_RESOLVER` is not being properly converted into nginx.conf config format? 

```
[root@p1 ~]# dig @198.51.100.1 postgresql.marathon.l4lb.thisdcos.directory

; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7_4.2 <<>> @198.51.100.1 postgresql.marathon.l4lb.thisdcos.directory
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58641
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;postgresql.marathon.l4lb.thisdcos.directory. IN        A

;; ANSWER SECTION:
postgresql.marathon.l4lb.thisdcos.directory. 5 IN A 11.255.191.179

;; Query time: 1 msec
;; SERVER: 198.51.100.1#53(198.51.100.1)
;; WHEN: Sat Feb 24 13:12:06 +08 2018
;; MSG SIZE  rcvd: 88
```

**Comment by pogzie** [comment]
From inside the container, the IP is reachable so I cant see why not it cant use it as a resolver.

```
bash-4.3# ping 198.51.100.1
PING 198.51.100.1 (198.51.100.1): 56 data bytes
64 bytes from 198.51.100.1: seq=0 ttl=64 time=0.073 ms
64 bytes from 198.51.100.1: seq=1 ttl=64 time=0.062 ms
```

**Comment by jprjr** [comment]
Regarding specifying multiple resolvers: they need to be put onto their own line in the nginx config, the docker start script just copies the parameter as-is to a single line.

One idea I've had is to run dnsmasq in the container. I have no way of knowing ahead of time what DNS servers are available, so I could have dnsmasq read in the hosts file, resolv.conf, etc, then just point multistreamer at that.

On February 24, 2018 12:15:53 AM EST, Pogz Ortile <notifications@github.com> wrote:
>From inside the container, the IP is reachable so I cant see why not it
>cant use it as a resolver.
>
>```
>bash-4.3# ping 198.51.100.1
>PING 198.51.100.1 (198.51.100.1): 56 data bytes
>64 bytes from 198.51.100.1: seq=0 ttl=64 time=0.073 ms
>64 bytes from 198.51.100.1: seq=1 ttl=64 time=0.062 ms
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jprjr/docker-multistreamer/issues/9#issuecomment-368201165

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pogzie** [comment]
I also tried just using one resolver, `"MULTISTREAMER_DNS_RESOLVER" : "198.51.100.1 ipv6=off"` no dice.

**Comment by jprjr** [comment]
Hey hey, I just pushed a new version - 11.0.4-3 - it has dnsmasq running in the Docker container. At startup, dnsmasq reads in /etc/hosts and /etc/resolv.conf. That way, things from /etc/hosts can be queried via DNS, anything else just gets forwarded to the default DNS servers for that container.

I updated the example overrides file to use dnsmasq by default, give that a try and let me know if it fixes your problem

**Comment by pogzie** [comment]
Will try over the weekend (been using Multistreamer via DC/OS heavily recently) and give feedback. Thanks man!

**Comment by pogzie** [comment]
Ok I had a little bit of time tonight. First I tried without the environment variable `"MULTISTREAMER_DNS_RESOLVER"`, still no go. Same errors. 

I added the line with one of my resolvers, `"MULTISTREAMER_DNS_RESOLVER" : "198.51.100.1 ipv6=off"` still no luck. 

I double checked everything, made sure that upon launching, it force-pulls the docker image (so im sure that its got the latest version). 

For what its worth, heres my `/etc/hosts` and `/etc/resolv.conf` from inside the container: 

```
bash-4.4# cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2      223a43b9474f
```

and 

```
bash-4.4# cat /etc/resolv.conf
# Generated by gen_resolvconf.py. Do not edit.
# Change configuration options by changing DC/OS cluster configuration.
# This file must be overwritten regularly for proper cluster operation around
# master failure.

options timeout:1
options attempts:3

nameserver 198.51.100.1
nameserver 198.51.100.2
nameserver 198.51.100.3
```

I observed something weird though. If I put in the environment variable `MULTISTREAMER_DNS_RESOLVER` I only get the Redis message `Unable to connect to redis: redis.marathon.l4lb.thisdcos.directory:6379` and no messages from Postgres. Pinging it seems to be reachable: 

```
bash-4.4# ping redis.marathon.l4lb.thisdcos.directory
PING redis.marathon.l4lb.thisdcos.directory (11.202.66.37): 56 data bytes
64 bytes from 11.202.66.37: seq=0 ttl=64 time=0.036 ms
64 bytes from 11.202.66.37: seq=1 ttl=64 time=0.057 ms
```

I did some Googling for some other ways to check the ports without telnet on the container, looks like its open from the perspective of the container too. 

```
bash-4.4# nc -z -v -w5 postgresql.marathon.l4lb.thisdcos.directory 5432
postgresql.marathon.l4lb.thisdcos.directory (11.255.191.179:5432) open
bash-4.4# nc -z -v -w5 redis.marathon.l4lb.thisdcos.directory 6379
redis.marathon.l4lb.thisdcos.directory (11.202.66.37:6379) open
```

**Comment by pogzie** [comment]
I checked your latest commits and for added sanity, I checked my container if it has `dnsmasq` installed and also got the logs for you (incase you're interested). 

```
bash-4.4# cat /var/log/dnsmasq/current
2018-02-28 16:10:42.823379500  dnsmasq[320]: started, version 2.78 cachesize 150
2018-02-28 16:10:42.823416500  dnsmasq[320]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6                                                                                no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
2018-02-28 16:10:42.823434500  dnsmasq[320]: reading /etc/resolv.conf
2018-02-28 16:10:42.823437500  dnsmasq[320]: using nameserver 198.51.100.1#53
2018-02-28 16:10:42.823438500  dnsmasq[320]: using nameserver 198.51.100.2#53
2018-02-28 16:10:42.823439500  dnsmasq[320]: using nameserver 198.51.100.3#53
2018-02-28 16:10:42.823479500  dnsmasq[320]: read /etc/hosts - 7 addresses
```

**Comment by pogzie** [comment]
I re-ran my tests with and without `MULTISTREAMER_DNS_RESOLVER` and if I dont specify anything there, I get a Redis and Postgres error. 

If I specified a resolver IP there, I only get Redis errors.

**Comment by jprjr** [comment]
Looks like in my start-up script, I forgot to use the new default DNS host (dnsmasq) if MULTISTREAMER_DNS_RESOLVER was blank/empty - it was still defaulting to 8.8.8.8

Just pushed 11.0.4-4 which should fix that.

**Comment by jprjr** [comment]
Regarding redis: looks like there's a legit bug, it seems that's a legit bug.

The docs for `lua-resty-redis` specify I should use `host, port, options` when connecting, in the past I could *swear* you used to be able to pass it a string like `127.0.0.1:6379` and have it work. Double-checking on all of that now.

**Comment by jprjr** [comment]
Just uploaded and tagged version 11.0.6, there's a build queued on Docker hub: https://hub.docker.com/r/jprjr/multistreamer/builds/bxowgwkzqewyrjxhe9jbfvw/

That has a fix to properly split up the redis host and port when making the connection.

**Comment by pogzie** [comment]
Nice. Will check. I shall keep you posted.

**Comment by pogzie** [comment]
Ok, I dont get any errors when loading the endpoint but when I type my login (from an existing redis/pgsql backend i have been using in my prod deployment) nothing happens. nothing on the logs, all i have is: 

```
bash-4.4# cat dnsmasq/current
2018-03-03 18:46:02.921195500  dnsmasq[319]: started, version 2.78 cachesize 150
2018-03-03 18:46:02.921228500  dnsmasq[319]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
2018-03-03 18:46:02.921230500  dnsmasq[319]: reading /etc/resolv.conf
2018-03-03 18:46:02.921231500  dnsmasq[319]: using nameserver 198.51.100.1#53
2018-03-03 18:46:02.921232500  dnsmasq[319]: using nameserver 198.51.100.2#53
2018-03-03 18:46:02.921233500  dnsmasq[319]: using nameserver 198.51.100.3#53
2018-03-03 18:46:02.921234500  dnsmasq[319]: read /etc/hosts - 7 addresses
2018-03-03 18:46:03.535985500  dnsmasq[319]: nameserver 198.51.100.3 refused to do a recursive query
2018-03-03 18:46:03.542992500  dnsmasq[319]: nameserver 198.51.100.1 refused to do a recursive query
```

I did not explicitly set the `MULTISTREAMER_DNS_RESOLVER`. I will try that next.

**Comment by pogzie** [comment]
Ok, so even with setting the DNS resolver to `"MULTISTREAMER_DNS_RESOLVER" : "198.51.100.1 ipv6=off"` the new isssue is still the same. Endpoint is accessible, but cant login. 

Logs inside the container are more quiet now: 

```
bash-4.4# cat /var/log/*/current
2018-03-03 19:09:04.827443500  dnsmasq[325]: started, version 2.78 cachesize 150
2018-03-03 19:09:04.827470500  dnsmasq[325]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
2018-03-03 19:09:04.827472500  dnsmasq[325]: reading /etc/resolv.conf
2018-03-03 19:09:04.827473500  dnsmasq[325]: using nameserver 198.51.100.1#53
2018-03-03 19:09:04.827474500  dnsmasq[325]: using nameserver 198.51.100.2#53
2018-03-03 19:09:04.827474500  dnsmasq[325]: using nameserver 198.51.100.3#53
2018-03-03 19:09:04.827475500  dnsmasq[325]: read /etc/hosts - 7 addresses
2018-03-03 19:09:04.847678500  Ran 0 migrations
```

Just for additional sanity checks, db/redis endpoints are still reachable from within the container: 

```
bash-4.4# ping redis.marathon.l4lb.thisdcos.directory
PING redis.marathon.l4lb.thisdcos.directory (11.202.66.37): 56 data bytes
64 bytes from 11.202.66.37: seq=0 ttl=64 time=0.054 ms
64 bytes from 11.202.66.37: seq=1 ttl=64 time=0.049 ms
64 bytes from 11.202.66.37: seq=2 ttl=64 time=0.045 ms
^C
--- redis.marathon.l4lb.thisdcos.directory ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.045/0.049/0.054 ms
bash-4.4# ping postgresql.marathon.l4lb.thisdcos.directory
PING postgresql.marathon.l4lb.thisdcos.directory (11.255.191.179): 56 data bytes
64 bytes from 11.255.191.179: seq=0 ttl=64 time=0.029 ms
64 bytes from 11.255.191.179: seq=1 ttl=64 time=0.046 ms
64 bytes from 11.255.191.179: seq=2 ttl=64 time=0.056 ms
^C
--- postgresql.marathon.l4lb.thisdcos.directory ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.029/0.043/0.056 ms
bash-4.4# nc -z -v -w5 postgresql.marathon.l4lb.thisdcos.directory 5432
postgresql.marathon.l4lb.thisdcos.directory (11.255.191.179:5432) open
bash-4.4# nc -z -v -w5 redis.marathon.l4lb.thisdcos.directory 6379
redis.marathon.l4lb.thisdcos.directory (11.202.66.37:6379) open
```

I might start with a fresh redis/postgres tomorrow but I doubt it would do any good. I've been killing/relaunching/suspending my prod multistreamer container and did not encounter any problems reconnecting/reusing the current instance of redis/postgres.

**Comment by jprjr** [comment]
I don't have this documented here on the Docker repo, but what happens if you set the REDIS_PREFIX environment variable to something other than "multistreamer/" ? IE, `REDIS_PREFIX: multistreamer-test/"

All the various redis keys are prefixed with "multistreamer/" by default, and it's expected that each instance of Multistreamer has its own instance of redis. If you change the prefix, you can run multiple instances of Multistreamer with the same instance of redis. Also, what backend are you using for auth?

**Comment by pogzie** [comment]
I will try changing the prefix and report back. 

I dont have special backends, just the default (the one wherein if you type a new user, it will save that new user and password). I was thinking of having this issue resolved first before moving into a new auth backend and write a guide how to setup multistreamer.

**Comment by jprjr** [comment]
Another thing to try out - using `ping` doesn't troubleshoot DNS resolution very well, since it will read in /etc/hosts and /etc/resolv.conf and use the system's default DNS resolver.

Since nginx will be using dnsmasq, I would try something like:

```
apk update
apk add bind-tools
dig @127.0.0.1 -p 5353 redis.marathon.l4lb.thisdcos.directory
```

That will let you know what IPs (if any) dnsmasq is returning to nginx.

**Comment by pogzie** [comment]
Good point. I ran the command you suggested: 

```
bash-4.4# dig @127.0.0.1 -p 5353 redis.marathon.l4lb.thisdcos.directory

; <<>> DiG 9.11.2-P1 <<>> @127.0.0.1 -p 5353 redis.marathon.l4lb.thisdcos.directory
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1245
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: df3d2eb12a4e24d2 (echoed)
;; QUESTION SECTION:
;redis.marathon.l4lb.thisdcos.directory.        IN A

;; ANSWER SECTION:
redis.marathon.l4lb.thisdcos.directory. 5 IN A  11.202.66.37

;; Query time: 1 msec
;; SERVER: 127.0.0.1#5353(127.0.0.1)
;; WHEN: Mon Mar 05 13:28:00 UTC 2018
;; MSG SIZE  rcvd: 95
```

But then again for Postgres, it seems to be failing: 

```
bash-4.4# dig @127.0.0.1 -p 5432 postgresql.marathon.l4lb.thisdcos.directory

; <<>> DiG 9.11.2-P1 <<>> @127.0.0.1 -p 5432 postgresql.marathon.l4lb.thisdcos.directory
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

But if I use the DNS server (without the port). Now im wondering if theres some outbound issues to 5432 using the DNS address of the load balanaced PG.

```
bash-4.4# dig @198.51.100.1  postgresql.marathon.l4lb.thisdcos.directory

; <<>> DiG 9.11.2-P1 <<>> @198.51.100.1 postgresql.marathon.l4lb.thisdcos.directory
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5327
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: c17f007039326df9 (echoed)
;; QUESTION SECTION:
;postgresql.marathon.l4lb.thisdcos.directory. IN        A

;; ANSWER SECTION:
postgresql.marathon.l4lb.thisdcos.directory. 5 IN A 11.255.191.179

;; Query time: 1 msec
;; SERVER: 198.51.100.1#53(198.51.100.1)
;; WHEN: Mon Mar 05 13:34:51 UTC 2018
;; MSG SIZE  rcvd: 100
```

**Comment by pogzie** [comment]
Whoops. Eyes completely failed me there. All good. 

```
bash-4.4# dig @127.0.0.1 -p 5353 redis.marathon.l4lb.thisdcos.directory

; <<>> DiG 9.11.2-P1 <<>> @127.0.0.1 -p 5353 redis.marathon.l4lb.thisdcos.directory
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19251
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 9910521a96743ec6 (echoed)
;; QUESTION SECTION:
;redis.marathon.l4lb.thisdcos.directory.        IN A

;; ANSWER SECTION:
redis.marathon.l4lb.thisdcos.directory. 5 IN A  11.202.66.37

;; Query time: 2 msec
;; SERVER: 127.0.0.1#5353(127.0.0.1)
;; WHEN: Mon Mar 05 13:47:28 UTC 2018
;; MSG SIZE  rcvd: 95

bash-4.4# dig @127.0.0.1 -p 5353 postgresql.marathon.l4lb.thisdcos.directory

; <<>> DiG 9.11.2-P1 <<>> @127.0.0.1 -p 5353 postgresql.marathon.l4lb.thisdcos.directory
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31860
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 938f11ff6b3363b5 (echoed)
;; QUESTION SECTION:
;postgresql.marathon.l4lb.thisdcos.directory. IN        A

;; ANSWER SECTION:
postgresql.marathon.l4lb.thisdcos.directory. 5 IN A 11.255.191.179

;; Query time: 1 msec
;; SERVER: 127.0.0.1#5353(127.0.0.1)
;; WHEN: Mon Mar 05 13:47:42 UTC 2018
;; MSG SIZE  rcvd: 100

bash-4.4#
```

**Comment by pogzie** [comment]
Any further help I can provide with this? I recently tested and sadly its still the same. Logs arent showing anything.

**Comment by jprjr** [comment]
I'm not sure what the problem could be - it seems like DNS is resolving, so all communication should be working. I'm really stumped on what this could be.

Maybe try changing the loglevel to "debug" - if you do that, go ahead and email them to me instead of posting them here. The debug logs can contain sensitive information.

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
